{"name": "test_login_with_valid_credentials", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'driver'", "trace": "self = <TestScripts.test_logintest.TestLogin object at 0x00000262EDEDFF20>\n\n    def test_login_with_valid_credentials(self):\n>       login_page = LoginPaged(self.driver)\nE       AttributeError: 'TestLogin' object has no attribute 'driver'\n\nTestScripts\\test_logintest.py:11: AttributeError"}, "start": 1710029650453, "stop": 1710029650453, "uuid": "a8f5ff3a-c344-4866-9b76-b93937d49911", "historyId": "551458a34115f6ea280e1d2064d25453", "testCaseId": "551458a34115f6ea280e1d2064d25453", "fullName": "TestScripts.test_logintest.TestLogin#test_login_with_valid_credentials", "labels": [{"name": "parentSuite", "value": "TestScripts"}, {"name": "suite", "value": "test_logintest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-6QKT7AQQ"}, {"name": "thread", "value": "25508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestScripts.test_logintest"}]}